# Generated by Django 6.0.1 on 2026-02-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default="1",
                help_text="Введите курс.",
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте превью курса.",
                null=True,
                upload_to="materials/photo_course",
                verbose_name="Превью курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте превью урока.",
                null=True,
                upload_to="materials/photo_lesson",
                verbose_name="Превью урока",
            ),
        ),
    ]
