# Generated by Django 6.0.1 on 2026-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson_course_alter_course_preview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса.",
                null=True,
                verbose_name="Описание курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(
                default="1",
                help_text="Укажите название курса.",
                max_length=200,
                verbose_name="Название курса",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание урока.",
                null=True,
                verbose_name="Описание урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link_video",
            field=models.CharField(
                blank=True,
                help_text="Добавьте ссылку на видео урока.",
                max_length=200,
                null=True,
                verbose_name="Ссылка на видео урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                default="",
                help_text="Укажите название урока.",
                max_length=200,
                verbose_name="Название урока",
            ),
            preserve_default=False,
        ),
    ]
