# Generated by Django 6.0.2 on 2026-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления курса.",
                null=True,
                verbose_name="Последнее обновление",
            ),
        ),
    ]
